### PR TITLE
[springlobby] Tune 9999

### PR DESCRIPTION
**Pull request by mfld-fr**
- Same owner as engine
- Remove X86 keyword (32-bit not more supported)
- Cleanup and tune 9999

### CODE REVIEW

**Comment by abma** [comment]
i'm at the point of giving you write permissions to this repo as its difficult for me to review changes as i'm not using gentoo.

any objections?

**Comment by abma** [comment]
> **Work in progress**
>     * Unmask AMD64 as tested stable for 15 days now

amd64 should be very stable: x86 isn't tested very well and should be avoided because of memory limitations.

**Comment by mfld-fr** [comment]
> i'm at the point of giving you write permissions to this repo as its difficult for me to review changes as i'm not using gentoo.
> 
> any objections?

No thank you. I am just a contributor who shares the fixes I made to thanks the community for that nice product. I won't contribute anymore after stopping to play S44.

**Comment by mfld-fr** [comment]
> > **Work in progress**
> > * Unmask AMD64 as tested stable for 15 days now
> 
> amd64 should be very stable: x86 isn't tested very well and should be avoided because of memory limitations.

OK, will put `~amd64` back and drop `~x86` as I understood that 32-bit is not more supported.

**Comment by abma** [comment]
can this be merged? the changes look minor.

i prefer/try to release early and often :-)

**Comment by mfld-fr** [comment]
Hello @abma, not yet, would like to complete my testing of `springlobby-9999` but I have urgent & personal matters to process first...

**Comment by abma** [comment]
sure, no worries and thanks for the quick response! :-)

**Comment by mfld-fr** [comment]
Hello @abma, found some time to complete this PR.

**Comment by abma** [comment]
looks good, thank you!

**Pull request merged**
