### PR TITLE
[spring] Update to 105.0 and tune 9999

### PR DESCRIPTION
**Pull request by mfld-fr**
One problem remains: missing 'lsl' folder in 105.0 source tarball - confirmed by @abma, now tracked by https://springrts.com/mantis/view.php?id=6446. Masked the 105.0 package until resolution.

`spring-9999` now follows the `master` branch and is equivalent today to 105.0. Sanity tested with latest S44 game.

### CODE REVIEW

**Comment by mfld-fr** [comment]
Patch `spring-9999-libdir` is an ugly & temporary one until https://github.com/spring/spring/pull/568.

**Comment by mfld-fr** [comment]
From what I understand from the project history, the `develop` branch is breaking the API used by the current major games. Therefore the `spring-9999.ebuild` should rather follow `master`, that is the current maintenance branch.

**Comment by mfld-fr** [comment]
@abma : now both Spring 0.105 and SpringLobby 0.273 packages are working again on current Gentoo with that PR. Could you please merge it ?

**Comment by abma** [comment]
> From what I understand from the project history, the `develop` branch is breaking the API used by the current major games. Therefore the `spring-9999.ebuild` should rather follow `master`, that is the current maintenance branch.

idk what spring-9999.ebuild should contain, but thats how development should work:

https://springrts.com/wiki/Development_guidelines#Engine_Branching_Model

the "develop" branch always contains the latest development, thus from time to time it breaks games.

**Comment by abma** [comment]
in other words, "master" will always be a stable + tagged release. so basicly a duplicate of the latest spring-(version).0.ebuild

**Comment by mfld-fr** [comment]
Thanks @abma for the explanation.

As the 105.0 source tarball is today broken, the `ebuild` for 9999 is for now a workaround to get the 105.0 from `master`, until that tarball is fixed and I can restore the `spring-105.0`.

`spring-9999` and `springlobby-0.273` are working quite well with this PR (I tested both packages with latest S44), so please merge that PR to have an overlay that works for the Gentoo users.

**Comment by mfld-fr** [comment]
Thanks @abma for the merge, and by the way, many thanks to keep the original ecosystem (engine + infra) working for all the games & guys that are not able to follow BAR evolution. Happy new year and best wishes for 2022 !

**Pull request merged**
